export const ACTIONS = {
  CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
  TOGGLE_ADD_TOURNAMENT: 'TOGGLE_ADD_TOURNAMENT',
  UPDATE_TOURNAMENT_ADD_FORM_FIELD: 'UPDATE_TOURNAMENT_ADD_FORM_FIELD',
  CLEAR_TOURNAMENT_ADD_FORM_FIELD: 'CLEAR_TOURNAMENT_ADD_FORM_FIELD',
  DISABLE_ADD_TOURNAMENT: 'DISABLE_ADD_TOURNAMENT'
}
