export const ACTIONS = {
  TOGGLE_DELETE_TOURNAMENT: 'TOGGLE_DELETE_TOURNAMENT',
  TOGGLE_EDIT_MATCHES: 'TOGGLE_EDIT_MATCHES',
  UPDATE_MATCH_EDIT_FORM_FIELD: 'UPDATE_MATCH_EDIT_FORM_FIELD',
  CLEAR_MATCH_EDIT_FORM_FIELD: 'CLEAR_MATCH_EDIT_FORM_FIELD',
  SUBMIT_UPDATE_MATCHES: 'SUBMIT_UPDATE_MATCHES',
  SUBMIT_DELETE_TOURNAMENT: 'SUBMIT_DELETE_TOURNAMENT'
}
