export const ACTIONS = {
  TOGGLE_EDIT_MATCHES: 'TOGGLE_EDIT_MATCHES',
  UPDATE_MATCH_EDIT_FORM_FIELD: 'UPDATE_MATCH_EDIT_FORM_FIELD',
  CLEAR_MATCH_EDIT_FORM_FIELD: 'CLEAR_MATCH_EDIT_FORM_FIELD',
  SUBMIT_EDIT_MATCHES: 'SUBMIT_EDIT_MATCHES'
}
